// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  console.error(
    `❌ Missing Supabase environment variables: ${missing.join(', ')}\n` +
    `Please check your .env file in the project root.`
  );
  
  // Show user-friendly error in browser console
  if (typeof window !== 'undefined') {
    console.error(
      '%c⚠️ Configuration Error',
      'color: red; font-size: 16px; font-weight: bold;',
      '\nMissing Supabase configuration. Please contact the administrator.'
    );
  }
}

// Create client with fallback to empty strings (will fail gracefully)
export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Test connection on initialization (only in browser)
if (typeof window !== 'undefined' && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  // Verify connection is working
  supabase
    .from('bikes')
    .select('id')
    .limit(1)
    .then(({ error }) => {
      if (error && error.message?.includes('Invalid API key')) {
        console.error('❌ Invalid Supabase API key. Please check your .env file.');
      } else if (error && error.message?.includes('Failed to fetch')) {
        console.warn('⚠️ Cannot connect to Supabase. Check your internet connection.');
      }
    })
    .catch(() => {
      // Silent fail - connection check only
    });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";